
import { Plant, GardenLogItem, PlantRecommendation, IdentificationResult, TimelineItem } from "../types";

declare const jspdf: any;

export const generatePlantPDF = (plant: Plant, lang: 'en' | 'nl', t: (key: string) => string) => {
  try {
    const { jsPDF } = jspdf;
    const doc = new jsPDF();
    const locale = lang === 'nl' ? 'nl-NL' : 'en-US';

    const pageWidth = doc.internal.pageSize.getWidth();
    const margin = 20;
    let yPos = 20;

    // Title
    doc.setFontSize(24);
    doc.setTextColor(22, 163, 74); // Green-600
    doc.text(plant.name, margin, yPos);
    yPos += 10;

    if (plant.scientificName) {
      doc.setFontSize(14);
      doc.setTextColor(100); // Grey
      doc.setFont("helvetica", "italic");
      doc.text(plant.scientificName, margin, yPos);
      yPos += 15;
    }

    // Image (if available)
    if (plant.imageUrl) {
        try {
            // Basic aspect ratio check
            const imgProps = doc.getImageProperties(plant.imageUrl);
            const ratio = imgProps.height / imgProps.width;
            const imgWidth = 80;
            const imgHeight = imgWidth * ratio;
            
            // Right align image
            const xPos = pageWidth - margin - imgWidth;
            doc.addImage(plant.imageUrl, 'JPEG', xPos, 20, imgWidth, imgHeight);
        } catch (e) {
            console.error("PDF Image Error", e);
        }
    }

    // Details
    doc.setFontSize(12);
    doc.setTextColor(0);
    doc.setFont("helvetica", "bold");
    doc.text(`${t('date_planted_label')}:`, margin, yPos);
    doc.setFont("helvetica", "normal");
    doc.text(plant.datePlanted ? new Date(plant.datePlanted).toLocaleDateString(locale) : 'N/A', margin + 40, yPos);
    yPos += 8;

    if (plant.isIndoor !== undefined) {
        doc.setFont("helvetica", "bold");
        doc.text("Type:", margin, yPos);
        doc.setFont("helvetica", "normal");
        doc.text(plant.isIndoor ? t('plant_type_indoor') : t('plant_type_outdoor'), margin + 40, yPos);
        yPos += 8;
    }

    yPos += 10;
    doc.setFontSize(16);
    doc.setTextColor(22, 163, 74);
    doc.text(t('description'), margin, yPos);
    yPos += 8;
    doc.setFontSize(10);
    doc.setTextColor(50);
    const descLines = doc.splitTextToSize(plant.description || t('no_desc'), pageWidth - 2 * margin);
    doc.text(descLines, margin, yPos);
    yPos += (descLines.length * 5) + 10;

    doc.setFontSize(16);
    doc.setTextColor(22, 163, 74);
    doc.text(t('care_label'), margin, yPos);
    yPos += 8;
    doc.setFontSize(10);
    doc.setTextColor(50);
    const careLines = doc.splitTextToSize(plant.careInstructions || t('no_instr'), pageWidth - 2 * margin);
    doc.text(careLines, margin, yPos);
    
    // Footer
    const pageHeight = doc.internal.pageSize.getHeight();
    doc.setFontSize(8);
    doc.setTextColor(150);
    doc.text("Generated by Flowerix", margin, pageHeight - 10);

    doc.save(`${plant.name}_Flowerix.pdf`);
    return true;
  } catch (e) {
    console.error("PDF Generation Error", e);
    return false;
  }
};

export const generateFullExport = (plants: Plant[], gardenLogs: GardenLogItem[], lang: 'en' | 'nl', t: (key: string) => string) => {
    try {
        const { jsPDF } = jspdf;
        const doc = new jsPDF();
        let yPos = 20;
        const margin = 20;
        const pageWidth = doc.internal.pageSize.getWidth();

        doc.setFontSize(22);
        doc.setTextColor(22, 163, 74);
        doc.text("Flowerix - Full Report", margin, yPos);
        yPos += 15;

        doc.setFontSize(16);
        doc.setTextColor(0);
        doc.text(`My Plants (${plants.length})`, margin, yPos);
        yPos += 10;

        plants.forEach((plant, index) => {
            if (yPos > 270) { doc.addPage(); yPos = 20; }
            doc.setFontSize(12);
            doc.setFont("helvetica", "bold");
            doc.text(`${index + 1}. ${plant.name}`, margin, yPos);
            doc.setFont("helvetica", "normal");
            doc.setFontSize(10);
            const summary = plant.description ? plant.description.substring(0, 100).replace(/\n/g, ' ') + '...' : 'No description';
            doc.text(summary, margin + 5, yPos + 5);
            yPos += 15;
        });

        yPos += 10;
        doc.setFontSize(16);
        doc.setTextColor(0);
        doc.text(`Garden Logs (${gardenLogs.length})`, margin, yPos);
        yPos += 10;
        
        gardenLogs.forEach((log, index) => {
            if (yPos > 270) { doc.addPage(); yPos = 20; }
            doc.setFontSize(12);
            doc.setFont("helvetica", "bold");
            doc.text(`${new Date(log.date).toLocaleDateString()} - ${log.title}`, margin, yPos);
            doc.setFont("helvetica", "normal");
            doc.setFontSize(10);
            doc.text(log.description || '', margin + 5, yPos + 5);
            yPos += 15;
        });

        doc.save(`Flowerix_Full_Export.pdf`);
        return true;
    } catch (e) {
        console.error("Export Error", e);
        return false;
    }
};

export const generateAdvicePDF = (recommendations: PlantRecommendation[], lang: 'en' | 'nl', t: (key: string) => string) => {
    try {
        const { jsPDF } = jspdf;
        const doc = new jsPDF();
        const margin = 20;
        let yPos = 20;
        const pageWidth = doc.internal.pageSize.getWidth();

        doc.setFontSize(22);
        doc.setTextColor(22, 163, 74);
        doc.text(t('advice_results_title'), margin, yPos);
        yPos += 15;

        recommendations.forEach((rec, idx) => {
            if (yPos > 250) { doc.addPage(); yPos = 20; }
            
            doc.setFontSize(14);
            doc.setTextColor(0);
            doc.setFont("helvetica", "bold");
            doc.text(`${idx + 1}. ${rec.name}`, margin, yPos);
            
            doc.setFontSize(10);
            doc.setTextColor(100);
            doc.setFont("helvetica", "italic");
            doc.text(rec.scientificName, margin + 5, yPos + 5);

            doc.setTextColor(0);
            doc.setFont("helvetica", "normal");
            const reasonLines = doc.splitTextToSize(rec.reason, pageWidth - 2 * margin);
            doc.text(reasonLines, margin + 5, yPos + 12);

            yPos += 15 + (reasonLines.length * 4);
        });

        // Footer
        const pageHeight = doc.internal.pageSize.getHeight();
        doc.setFontSize(8);
        doc.setTextColor(150);
        doc.text("Generated by Flowerix", margin, pageHeight - 10);

        doc.save("Flowerix_Advice.pdf");
        return true;
    } catch (e) {
        console.error("Advice PDF Error", e);
        return false;
    }
};

export const generateIdentificationPDF = (result: IdentificationResult, lang: 'en' | 'nl', t: (key: string) => string) => {
    try {
        const { jsPDF } = jspdf;
        const doc = new jsPDF();
        const margin = 20;
        let yPos = 20;
        const pageWidth = doc.internal.pageSize.getWidth();

        // Header
        doc.setFontSize(22);
        doc.setTextColor(22, 163, 74);
        doc.text(result.name, margin, yPos);
        yPos += 8;

        doc.setFontSize(12);
        doc.setTextColor(100);
        doc.setFont("helvetica", "italic");
        doc.text(result.scientificName || '', margin, yPos);
        yPos += 15;

        // Sections
        const addSection = (title: string, content: string) => {
            if (yPos > 250) { doc.addPage(); yPos = 20; }
            doc.setFontSize(14);
            doc.setTextColor(0);
            doc.setFont("helvetica", "bold");
            doc.text(title, margin, yPos);
            yPos += 6;
            
            doc.setFontSize(10);
            doc.setFont("helvetica", "normal");
            const lines = doc.splitTextToSize(content || 'N/A', pageWidth - 2 * margin);
            doc.text(lines, margin, yPos);
            yPos += (lines.length * 5) + 10;
        };

        addSection(t('description'), result.description);
        addSection(t('id_soil_care'), result.soil);
        addSection(t('id_climate'), result.climate);
        addSection(t('id_size'), result.size);
        addSection(t('id_pruning'), result.pruning);

        // Footer
        const pageHeight = doc.internal.pageSize.getHeight();
        doc.setFontSize(8);
        doc.setTextColor(150);
        doc.text("Identified by Flowerix", margin, pageHeight - 10);

        doc.save(`${result.name}_ID.pdf`);
        return true;
    } catch (e) {
        console.error("ID PDF Error", e);
        return false;
    }
};

export const generateSummaryPDF = (content: string, lang: 'en' | 'nl', t: (key: string) => string) => {
    try {
        const { jsPDF } = jspdf;
        const doc = new jsPDF();
        const margin = 20;
        const pageWidth = doc.internal.pageSize.getWidth();
        let yPos = 20;

        doc.setFontSize(18);
        doc.setTextColor(22, 163, 74);
        doc.text(t('summary_title'), margin, yPos);
        yPos += 10;

        doc.setFontSize(11);
        doc.setTextColor(50);
        const lines = doc.splitTextToSize(content, pageWidth - 2 * margin);
        for (let i = 0; i < lines.length; i++) {
            if (yPos > 280) { doc.addPage(); yPos = 20; }
            doc.text(lines[i], margin, yPos);
            yPos += 6;
        }

        doc.save('Flowerix_Summary.pdf');
        return true;
    } catch (e) {
        console.error('Summary PDF Error', e);
        return false;
    }
};

export const generateNotebookPDF = (items: TimelineItem[], startDate: Date, endDate: Date, lang: 'en' | 'nl', t: (key: string) => string) => {
    try {
        const { jsPDF } = jspdf;
        const doc = new jsPDF();
        const locale = lang === 'nl' ? 'nl-NL' : 'en-US';
        const margin = 20;
        let yPos = 20;
        const pageWidth = doc.internal.pageSize.getWidth();

        doc.setFontSize(22);
        doc.setTextColor(22, 163, 74);
        doc.text(t('notebook_title'), margin, yPos);
        yPos += 10;

        doc.setFontSize(10);
        doc.setTextColor(100);
        const rangeStr = `${startDate.toLocaleDateString(locale)} - ${endDate.toLocaleDateString(locale)}`;
        doc.text(rangeStr, margin, yPos);
        yPos += 15;

        items.forEach(item => {
            if (yPos > 270) { doc.addPage(); yPos = 20; }

            const dateStr = new Date(item.date).toLocaleDateString(locale);
            
            // Draw line
            doc.setDrawColor(200);
            doc.line(margin, yPos, pageWidth - margin, yPos);
            yPos += 8;

            // Date & Type
            doc.setFontSize(10);
            doc.setTextColor(100);
            doc.setFont("helvetica", "bold");
            const typeLabel = item.type === 'NOTE' ? t('add_note') : t('add_task');
            doc.text(`${dateStr} • ${typeLabel}`, margin, yPos);
            yPos += 6;

            // Title
            doc.setFontSize(12);
            doc.setTextColor(0);
            doc.text(item.title, margin, yPos);
            
            // Done status for tasks
            if (item.type === 'TASK') {
                doc.setFontSize(8);
                const status = item.isDone ? t('task_done') : 'Todo';
                const w = doc.getTextWidth(status);
                doc.setTextColor(item.isDone ? [34, 197, 94] : [107, 114, 128]);
                doc.text(`[${status}]`, pageWidth - margin - w - 5, yPos);
            }
            yPos += 6;

            // Desc
            if (item.description) {
                doc.setFontSize(10);
                doc.setTextColor(60);
                doc.setFont("helvetica", "normal");
                const descLines = doc.splitTextToSize(item.description, pageWidth - 2 * margin);
                doc.text(descLines, margin, yPos);
                yPos += (descLines.length * 5) + 5;
            } else {
                yPos += 5;
            }
        });

        doc.save("Flowerix_Notebook.pdf");
        return true;
    } catch (e) {
        console.error("Notebook PDF Error", e);
        return false;
    }
};

export const generateProfessorPDF = (title: string, content: string, imageUrl: string | null, lang: 'en' | 'nl', t: (key: string) => string) => {
    try {
        const { jsPDF } = jspdf;
        const doc = new jsPDF();
        const margin = 20;
        let yPos = 20;
        const pageWidth = doc.internal.pageSize.getWidth();

        // Header
        doc.setFontSize(22);
        doc.setTextColor(79, 70, 229); // Indigo-600
        doc.text("The Professor", margin, yPos);
        yPos += 10;

        doc.setFontSize(14);
        doc.setTextColor(0);
        doc.setFont("helvetica", "bold");
        doc.text(title, margin, yPos);
        yPos += 10;

        // Image
        if (imageUrl) {
            try {
                const imgProps = doc.getImageProperties(imageUrl);
                const ratio = imgProps.height / imgProps.width;
                const imgWidth = 100;
                const imgHeight = imgWidth * ratio;
                
                // Check page break
                if (yPos + imgHeight > 250) { doc.addPage(); yPos = 20; }
                
                doc.addImage(imageUrl, 'JPEG', margin, yPos, imgWidth, imgHeight);
                yPos += imgHeight + 10;
            } catch (e) {
                console.error("PDF Image Error", e);
            }
        }

        // Content
        doc.setFontSize(11);
        doc.setTextColor(50);
        doc.setFont("helvetica", "normal");
        
        // Remove markdown codes
        const cleanContent = content
            .replace(/#{1,6}\s/g, '') 
            .replace(/\*\*/g, '')
            .replace(/\*/g, '')
            .replace(/`/g, '');

        const lines = doc.splitTextToSize(cleanContent, pageWidth - 2 * margin);
        
        // Loop through lines to handle paging better
        for(let i=0; i<lines.length; i++) {
             if (yPos > 280) {
                 doc.addPage();
                 yPos = 20;
             }
             doc.text(lines[i], margin, yPos);
             yPos += 5;
        }

        doc.save("Professor_Answer.pdf");
        return true;
    } catch (e) {
        console.error("Professor PDF Error", e);
        return false;
    }
};
